### ISSUE TITLE
Moving towards 1.0 version: roadmap & feedback wanted

### ISSUE THREAD

**Issue by pechorin** [pechorin/any-jump.vim#40]
Current roadmap:

- [ ] paths priorities for better search results
- [ ] [nvim] ability to jump through preview text (and another keyword)
- [ ] show latest N search keywords in popup to save jumping history
- [ ] tags support

Please share your ideas.

**Comment by pechorin** [comment]
@pyrho @markwu @khalidchawtany @watzon please let me know about missing features/staff you will like .)

**Comment by watzon** [comment]
Mostly I'm excited to get ctags support. I feel like that will make a huge difference.

**Comment by marlun** [comment]
I'm impressed how nice this works without much setup! 👍 In my experience these kind of plugins can often add too many features and become somewhat of a behemoth, I'm more for keeping it lightweight 😄

**Comment by pechorin** [comment]
@marlun yeah, where are problem with ui complexity and i think i should care about it specially in context of ctags/refactoring support, think this new features should be pluggable.

**Comment by pechorin** [comment]
@watzon i do some research on tags support question. i use gutentags for tags generation and this works great for autocompletion. i also noticed what tags file contains the same definitions results as any-jump do via syntax regexp rules. So i see only one reason to do tags support — is for perfomance, because sometimes (specially on large code base) searching for definitions can span to 3 and more seconds. Will think about this.

**Comment by pechorin** [comment]
So, tags support is something what we do already, via our regexp rules engine.

**Comment by watzon** [comment]
There is another reason to support tags. There are already tons of languages that ctags has support for, and it's really easy to write your own .ctags file to add support for another language. If you want to add support for another language here right now you have to make a pull request.

**Comment by pechorin** [comment]
Hmm, okay, i looked at ctags support languages list and it's impressive.

**Comment by watzon** [comment]
Yeah, and super easy to add support for a new language. So I think it's definitely worth doing.

**Comment by markwu** [comment]
I use `ctags`, `global(gtags)` and `any-jump` at the same time, actually I like the simple of `any-jump`.

1. I don't need to `re-generate` `tags` file atfer I edited the files. I can just hit `<leader>j` to find all definitions and references on the fly. (altough, it might be slow for very big project)
2. `ctags` only support definitions, no references.
3. `global(gtags)` support far fewer languages than `ctags`, but it supports references with it's native parsing engine. It can support more languages through embed `ctags`/`pygements` into `global(gtags)`, but no references.

That's why I am so impressed with any-jump. It just fill the gap between `ctags` and `grep-like` tools. I like it.

If you want to support `ctags`, I will suggest use the strength of `ctags`, just use it to find definitions as an enhanced engine.

But, keep references with current implementation.

So, any-jump will have three sections  when ctags support ready:

1. definitions from any-jump (through current regexp rules), just find an easy for user to extend it.
2. definitions from ctags (through ctags files), from `tselect` command
3. references from any-jump

Just my two cents!

**Comment by georgijd** [comment]
Hi, what a great project!

I'd like to suggest adding optional borders around the floating windows :) 
```
[
  "┌",
  "─",
  "┐",
  "│",
  "┘",
  "─",
  "└",
  "│"
]
```

Example plugins that have that feature are https://github.com/junegunn/fzf.vim and https://github.com/antoinemadec/coc-fzf

Also, it would be great to be able to set the background colour of the popup.

Thanks!

**Comment by kylepollina** [comment]
Hello, love this plugin so far. A feature request I would like to see added would be the ability to move up a directory. Unless that would be handled with ctags/gutentags, my idea would be maybe something is defined in the parent directory, it would be useful to hit a button to 'go up one directory and re-run search'. Thanks!

**Comment by goodboy** [comment]
FWIW, i've been able to do a rewrite for modern `nvim` (with much help from the botz) which is nearly ready for public testing.

If anyone is interested please ping me 👍🏼

It'd also be good to know if there's particular place to post a link to the new repo (once ready) in an `any-jump`-repo (issue?) user facing way so it's discoverable for anyone yearning for a more modernized rework of this **amazing plugin** 🙏🏼
